-
  name:  'TYPO3 Neos - Frontend - Redirect'
  uriPattern: '{path}'
  defaults:
    '@package':    'Your.Package'
    '@controller': 'Frontend\NotFound'
    '@action':     'index'
    '@format':     'html'
  routeParts:
    'path':
      handler:     'MOC\Redirects\Routing\RedirectFrontendNodeRoutePartHandler'